src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 9, scale: 2)]
    private ?string $price = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $owner = null;

    #[ORM\Column]
    private ?int $total = null;

    #[ORM\Column(options: ["default" => 0])]
    #[Assert\Expression(expression: "this.getTotalReserved() <= this.getTotal()",
                        message: "The reserved total must be less than or equal to the total.")]
    private ?int $total_reserved = null;

    #[ORM\Column(length: 32)]
    private ?string $sku = null;

    #[ORM\ManyToMany(targetEntity: ProductProperty::class, inversedBy: 'products')]
    private Collection $properties;

    #[ORM\ManyToOne(inversedBy: 'product')]
    private ?Cart $cart = null;

    public function __construct()
    {
        $this->properties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(int $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function getTotalReserved(): ?int
    {
        return $this->total_reserved;
    }

    public function setTotalReserved(int $total_reserved): static
    {
        $this->total_reserved = $total_reserved;

        return $this;
    }

    public function getSku(): ?string
    {
        return $this->sku;
    }

    public function setSku(string $sku): static
    {
        $this->sku = $sku;

        return $this;
    }

    /**
     * @return Collection<int, ProductProperty>
     */
    public function getProperties(): Collection
    {
        return $this->properties;
    }

    public function addProperty(ProductProperty $property): static
    {
        if (!$this->properties->contains($property)) {
            $this->properties->add($property);
        }

        return $this;
    }

    public function removeProperty(ProductProperty $property): static
    {
        $this->properties->removeElement($property);

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): static
    {
        $this->cart = $cart;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Product;
use App\Entity\ProductProperty;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    private $entityManager;

    public function __construct(
        private LoggerInterface $logger,
        private Security        $security,
        EntityManagerInterface  $entityManager
    )
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $categoryRepository = $this->entityManager->getRepository(Category::class);

        $builder
            ->add('name')
            ->add('description')
            ->add('price')
            ->add('total')
            ->add('total_reserved')
            ->add('sku')
            ->add('category', EntityType::class, [
                'choice_label' => function ($category) {
                    return $category->getName();
                },
                'class' => Category::class,
                'label' => 'Category',
                'multiple' => false,
                'required' => true,
            ]);

        $user = $this->security->getUser();
        if (!$user) {
            throw new \LogicException(
                'The cannot be used without an authenticated user!'
            );
        }

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) use ($user) {
            $form = $event->getForm();
            $form->add('owner', EntityType::class, [
                'choice_label' => function ($user) {
                    return $user->getName();
                },
                'choices' => [$user],
                'data' => $user,
                'class' => User::class,
                'label' => 'Owner',
                'required' => true,
            ]);
        });

        $formModifier = function (FormInterface $form, Category $category = null) {
            $properties = null === $category ? [] : $category->getProductProperties();

            $form->add('properties', EntityType::class, [
                'choice_label' => function ($prop) {
                    return $prop->getName();
                },
                'choices' => $properties,
                'class' => ProductProperty::class,
                'label' => 'Property',
                'multiple' => true,
                'required' => true,
                'group_by' => function ($choice, $key, $value) {
                    return $choice->getCode();
                },
            ]);
        };

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formModifier, $categoryRepository) {
                $data = $event->getData();
                $category = $data->getCategory();
                if ($category == Null) {
                    $category = $categoryRepository -> getFirstCategory();
                }

                $formModifier($event->getForm(), $category);
            }
        );

        $builder->get('category')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) use ($formModifier) {
                $data = $event->getForm()->getData();
                $formModifier($event->getForm()->getParent(), $data);
            }
        );

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use App\Service\ProductValidationService;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use function Symfony\Component\Translation\t;

#[IsGranted('ROLE_MERCHANT')]
#[Route('/merchant/product')]
class ProductController extends AbstractController
{
    #[Route('/', name: 'app_product_index', methods: ['GET'])]
    public function index(ProductRepository $productRepository): Response
    {
        $user = $this->getUser();
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findByUser($user),
            'merchant' => $this->getUser()
        ]);
    }

    #[Route('/new', name: 'app_product_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProductRepository $productRepository,
        ProductValidationService $productValidationService,
        LoggerInterface $logger,
    ): Response
    {
        $product = new Product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        $data = $request->get('product');
        $is_valid = $productValidationService->validate($product, $data, function ($key, $msg) {
            $this->addFlash($key, $msg);
        });

        if ($is_valid && $form->isSubmitted() && $form->isValid()) {
            $productRepository->save($product, true);

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product/new.html.twig', [
            'product' => $product,
            'form' => $form,
            'merchant' => $this->getUser()
        ]);
    }

    #[Route('/{id}', name: 'app_product_show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(Product $product): Response
    {
        return $this->render('product/show.html.twig', [
            'product' => $product,
            'merchant' => $this->getUser()
        ]);
    }

    #[Route('/{id}/edit', name: 'app_product_edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(Request $request, Product $product, ProductRepository $productRepository,
        ProductValidationService $productValidationService): Response
    {
        $user = $this->getUser();
        if (!$productRepository->isProductOwner($product, $user)) {
            throw $this->createAccessDeniedException('Access denied');
        }
        $isCheck = $request->request->get('_type', false);
        if ($isCheck) {
            $product = new Product();
        }
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        $data = $request->get('product');
        $is_valid = $productValidationService->validate($product, $data, function ($key, $msg) {
            $this->addFlash($key, $msg);
        });

        if ($is_valid && $form->isSubmitted() && $form->isValid()) {
            $productRepository->save($product, true);

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form,
            'merchant' => $this->getUser()
        ]);
    }

    #[Route('/{id}', name: 'app_product_delete', requirements: ['id' => '\d+'], methods: ['POST'])]
    public function delete(Request $request, Product $product, ProductRepository $productRepository,
        LoggerInterface $logger): Response
    {
        $user = $this->getUser();
        if (!$productRepository->isProductOwner($product, $user)) {
            throw $this->createAccessDeniedException('Access denied');
        }
        $logger->error("-----------------------------------------------");
        $logger->error("RS: {$productRepository->countPurchases($product)}");
        if ($productRepository->countPurchases($product) != 0) {
            $this->addFlash('product_delete', 'Submit all purchases first');
            return $this->redirectToRoute('app_product_show', ['id'=>$product->getId()], Response::HTTP_SEE_OTHER);
        }
        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $productRepository->remove($product, true);
        }

        return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/csv', name: 'app_product_to_csv', methods: ['GET'])]
    public function exportProductsToCsv(Request $request, ProductRepository $productRepository): Response
    {
        $user = $this->getUser();
        $response = new StreamedResponse(function () use ($user, $productRepository) {
            $handle = fopen('php://output', 'w');

            $headers = ['ID', 'SKU', 'Name', 'Price', 'Description', 'Total', 'Total Reserved'];
            fputcsv($handle, $headers);

            $products = $productRepository->findByUser($user);

            foreach ($products as $product) {
                $data = [
                    $product->getId(),
                    $product->getSku(),
                    $product->getName(),
                    $product->getPrice(),
                    $product->getDescription(),
                    $product->getTotal(),
                    $product->getTotalReserved(),
                ];

                fputcsv($handle, $data);
            }

            fclose($handle);
        });

        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment; filename="products.csv"');

        return $response;
    }

}

templates/product/_delete_form.html.twig
<form method="post" action="{{ path('app_product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    {% for flash in app.flashes('product_delete') %}
        <div class="alert alert-danger" role="alert">{{ flash }}</div>
    {% endfor %}
    <button class="btn btn-danger">Delete</button>
</form>

templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    {% for flash_error in app.flashes('verify_product') %}
        <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
    {% endfor %}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

<script>
    let $category = $('#product_category')
    let $properties = $('#product_properties')
    $category.change(updateProps);

    function updateProps() {
        let $form = $(this).closest('form')
        let data = {
            '_type': 'check',
            [$category.attr('name')]: $category.val()
        }
        $.ajax({
            url : $form.attr('action'),
            type: $form.attr('method'),
            data : data,
            complete: function(html) {
                $('#product_properties').replaceWith(
                    $(html.responseText).find('#product_properties')
                );
            }
        });
    }

</script>

templates/product/edit.html.twig
{% extends 'merchant/base_form.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block form_name %}Edit Product{% endblock %}
{% block form %}

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_product_index') }}">back to list</a>

{#    {{ include('product/_delete_form.html.twig') }}#}
{% endblock %}

templates/product/index.html.twig
{% extends 'merchant/base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block container %}
    <div class="">
        <h3>Product index</h3>

        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Sku</th>
                <th>Price</th>
                <th>Total</th>
                <th>Total reserved</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.description }}</td>
                    <td>{{ product.category.name }}</td>
                    <td>{{ product.sku }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.total }}</td>
                    <td>{{ product.totalReserved }}</td>
                    <td>
                        <a href="{{ path('app_product_show', {'id': product.id}) }}">show</a>
                        <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{{ path('app_product_new') }}">Create new</a>
        <a href="{{ path('app_product_to_csv') }}">Products to csv</a>
    </div>
{% endblock %}

templates/product/new.html.twig
{% extends 'merchant/base_form.html.twig' %}

{% block title %}New Product{% endblock %}

{% block form_name %}Create new Product{% endblock %}
{% block form %}

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('app_product_index') }}">back to list</a>
{% endblock %}

templates/product/show.html.twig
{% extends 'merchant/base.html.twig' %}

{% block title %}Product{% endblock %}

{% block container %}
    <div class="">
        <h3>Product</h3>

        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ product.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ product.description }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ product.price }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ product.total }}</td>
            </tr>
            <tr>
                <th>Total_reserved</th>
                <td>{{ product.totalReserved }}</td>
            </tr>
            <tr>
                <th>Sku</th>
                <td>{{ product.sku }}</td>
            </tr>
            </tbody>
        </table>

        <a href="{{ path('app_product_index') }}">back to list</a>

        <a href="{{ path('app_product_edit', {'id': product.id}) }}">edit</a>

        {{ include('product/_delete_form.html.twig') }}
    </div>
{% endblock %}